jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/clinic?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: # your email
    password: # your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            trust: "smtp.gmail.com"
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG